In [2]:
import numpy as np


In [3]:

a = np.array([1,3,4,5])
b = np.array([5,6,7,8,])


In [4]:
# Multiplication
c = a*b
print(c)

[ 5 18 28 40]


In [8]:
# Getting the dimensions
c.shape


(4,)

In [6]:
# Getting the size
c.itemsize

8

In [31]:
# Spesific element
c[0]

5

In [33]:
# Creating a two dimentional array using reshape()
array = np.arange(20).reshape(4,5)

array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
array.shape

(4, 5)

In [35]:
# Getting a spesific row eg the first row
array[0,:]

array([0, 1, 2, 3, 4])

In [36]:
# Getting the third column
array[:,2]

array([ 2,  7, 12, 17])

In [37]:
# Lets make it more fancy ie select from the first row the 1st to the 4th column stepby 2
array[0,1:5:2]

array([1, 3])

In [39]:
# initialize an array of all zeros
all_zeros = np.zeros(5)
all_zeros

array([0., 0., 0., 0., 0.])

In [40]:
# 2D array of ones
all_ones = np.ones((2,3))
all_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# An array of any other number declare the shape, followed by the number then an optional datatype
other = np.full((2,3),6)
other

array([[6, 6, 6],
       [6, 6, 6]])

In [46]:
# Random number initialisation for decimals
new = np.random.rand(3,2)
new

array([[0.02446577, 0.95096486],
       [0.2901606 , 0.40876771],
       [0.26574051, 0.04934102]])

In [49]:
# integers you can give the stack value , if none is given it will start from 0
new2 = np.random.randint(4,7,(3,4))
new2

array([[5, 5, 4, 5],
       [4, 4, 4, 6],
       [5, 4, 4, 5]])

In [51]:
# identity matrix
matrix = np.identity(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])